language: python
matrix:
  include:
    - python: 2.6
      dist: trusty
    - python: 2.7
    - python: 3.3
      dist: trusty
    - python: 3.4
      dist: trusty
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: nightly
    - python: pypy
    - python: pypy3.5
    - python: pypy3.6-7.1.1
  allow_failures:
    - python: nightly

before_install:
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
      echo "No pull requests can be sent to the master branch" 1>&2;
      exit 1;
    fi
  - pip install codecov
install:
  - python scripts/ci/install
  - python scripts/ci/install-check
script:
  - python scripts/ci/run-tests
  - python scripts/ci/run-check
after_success:
  - rm tests/coverage.xml && mv tests/.coverage ./ && codecov
